



// HERENCIA

// class persona {
//     constructor(name, age){
//         this.name =name,
//         this.age=age
//     }

//     saludar(){
//         alert('hola que tal '+ this.name)
//     }
// }

// class estudiante extends persona {
//     constructor(name, age, comision){
//         super(name,age);
//         this.comision=comision;
//     }
// }

// let ivan = new estudiante ('ivan', 30, 'comision: 59i')




